### ISSUE TITLE
unic_langid_impl should be re-exported

### ISSUE THREAD

**Issue by kakserpom** [mondeja/leptos-fluent#108]
`pub use unic_langid_impl;` please

**Comment by mondeja** [comment]
What is your purpose? If you want `LanguageIdentifier` you can get it from fluent-templates directly, using `fluent_templates::LanguageIdentifier`.

**Comment by kakserpom** [comment]
@mondeja Thank you! :-) My silly workaround was to add unic_langid_impl as a dependency.
