### ISSUE TITLE
`cargo leptos watch` for FTL files

### ISSUE THREAD

**Issue by kakserpom** [mondeja/leptos-fluent#109]
Please make it happen :-)

**Comment by mondeja** [comment]
I've tried to do that but I was not able to get it to work using the `watch-additional-files` option of cargo-leptos. I have to look at it again, any suggestions on this? Perhaps I need to include the files on server side too using `include_bytes!`.

**Comment by mondeja** [comment]
See #121. You need to use `watch-additional-files` metadata option of `[package.metadata.leptos]` pointing to your locales folder, using a relative path from your _Cargo.toml_ of your crate or workspace.
