### ISSUE TITLE
Bug: cookie needs a way to set path/domain/expires

### ISSUE THREAD

**Issue by kakserpom** [mondeja/leptos-fluent#118]
There should be a way to adjust `path` and `domain` settings as well as `expires`.

Now that the `path` is omitted, it defaults to the current `location.pathname`, so naturally it leads to this:

<img width="344" alt="image" src="https://github.com/mondeja/leptos-fluent/assets/175350/024803ef-d6e5-47d8-9f85-c5832584d1e6">

Which can be really frustrating for users.

**Comment by mondeja** [comment]
Do you have any proposal for the API? I didn't used the cookie feature.

**Comment by kakserpom** [comment]
You can just introduce `cookie_path`, `cookie_domain` and `cookie_expires` parameters. `cookie_path` is recommended to be set to "/" (this should be noted somewhere).

**Comment by mondeja** [comment]
I'm introducing `cookie_attrs: "..."` so you can set whatever attributes you want, for example: `cookie_attrs: "SameSite=Strict; path=/; Secure; max-age: 600"`. See https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie#write_a_new_cookie

**Comment by mondeja** [comment]
This will be released in a few minutes on v0.0.37

**Comment by kakserpom** [comment]
Not particularly the Rust way, but it will do :-)
