### ISSUE TITLE
SSR for sync_html_tag_lang and sync_html_tag_dir

### ISSUE THREAD

**Issue by kakserpom** [mondeja/leptos-fluent#155]
`lang` and `dir` attributes in `<html>` are missing in SSR.

**Comment by mondeja** [comment]
But in SSR there is not a rendered tree to pick from it a `<html>` tag. Even `web_sys` can't be used. Do you have any suggestion about how could be implemented?

**Comment by kakserpom** [comment]
https://book.leptos.dev/metadata.html#body-and-html

**Comment by kakserpom** [comment]
```
pub fn App() -> impl IntoView {
    // ...

    #[component(transparent)]
    #[cfg(feature = "ssr")]
    fn SsrHtmlTag() -> impl IntoView {
        use leptos_fluent::expect_i18n;
        let ssr_lang = expect_i18n().language.get_untracked();
        view! {
            <Html
                lang=ssr_lang.id.to_string()
                dir=ssr_lang.dir.to_string()
            />
        }
    }
    #[component(transparent)]
    #[cfg(not(feature = "ssr"))]
    fn SsrHtmlTag() -> impl IntoView {}

    view! {
        <SsrHtmlTag/>
        // ...
```

**Comment by mondeja** [comment]
Would you like to open a PR?

**Comment by kakserpom** [comment]
Yes, why not. I am just not sure how to incorporate this seamlessly. I guess we don't want people to have to insert `<SsrHtmlTag/>` manually.

**Comment by mondeja** [comment]
Can you please check if #161 works for you?

```rust
use leptos_fluent::SsrHtmlTag;
```

**Comment by kakserpom** [comment]
_Haha, I missed your PR and sent you my own. Very similar, so much so that I didn't have to modify my userland code to switch._

It works, but we need to respect `sync_html_tag_lang` and `sync_html_tag_dir` flags.

**Comment by kakserpom** [comment]
Btw,

```let sync_html_tag_dir_quote = {
        let effect_quote = quote! {
            ::leptos::create_effect(move |_| {
                use wasm_bindgen::JsCast;
                _ = ::leptos::document()
                    .document_element()
                    .unwrap()
                    .unchecked_into::<::leptos_fluent::web_sys::HtmlElement>()
                    .set_attribute(
                        "dir",
                        #get_language_quote.dir.as_str(),
                    );
            });
        };
```

 can be replaced with `<Html>` with reactive properties.

That way you can do it in one fashion in both CSR and SSR.

**Comment by mondeja** [comment]
Feel free to open a PR, not found a way to make it work.

**Comment by mondeja** [comment]
Since v0.1.14 the component is not needed anymore and has been deprecated. Now `sync_html_tag_lang` and `sync_html_tag_dir` do all the work even on SSR.
