### ISSUE TITLE
Possibility to split fluent files

### ISSUE THREAD

**Issue by johansmitsnl** [mondeja/leptos-fluent#201]
I want to organize the fluent translation files into separate files for each section of the application. But it seems that only 1 file is supported?

I would like to make:
```
en
  |- main.ftl
  |- profile.ftp
nl
  |- main.ftl
  |- profile.ftp
```

**Comment by mondeja** [comment]
*profile.ftp*? Are you sure you are using the correct file extension?

**Comment by mondeja** [comment]
I just copy-pasted the fluent-templates implementation and adapted it for leptos-fluent, which yes indeed supports multiple files, but need to be in the *.ftl* file extension.

**Comment by johansmitsnl** [comment]
It was indeed the extension issue, thanks for the support!
