### ISSUE TITLE
Upgrade to leptos 0.7

### ISSUE THREAD

**Issue by mscofield0** [mondeja/leptos-fluent#259]
Leptos 0.7-rc1 is in a stable state API-wise and I would like to start porting over to it, but `leptos-fluent` is lagging behind currently.

**Comment by mondeja** [comment]
You can temporally use the `leptos-v0.7` branch, see #228

**Comment by mscofield0** [comment]
How quickly can you release 0.2? I'm depending on leptos-fluent a lot and I'm in a time-critical position at the moment.

**Comment by mondeja** [comment]
I'll try to release ASAP.

**Comment by mondeja** [comment]
v0.2.0 has been released.
