### ISSUE TITLE
Upgrade `fluent-templates` to 0.2

### ISSUE THREAD

**Issue by mscofield0** [mondeja/leptos-fluent#266]
I depend on both `leptos-fluent` and `fluent-templates` and if one of them isn't the same version, my types would have a mismatch. Can you please upgrade it to 0.2?

**Comment by mondeja** [comment]
I think that you're referring to v0.12. Was released yesterday, see https://github.com/mondeja/leptos-fluent/blob/master/CHANGELOG.md#2024-12-23---021

**Comment by mscofield0** [comment]
No, I really meant `fluent-templates@0.2`: https://github.com/XAMPPRocky/fluent-templates/pull/85

This was merged yesterday.
