### ISSUE TITLE
fluent-templates version mismatch

### ISSUE THREAD

**Issue by johansmitsnl** [mondeja/leptos-fluent#267]
I have this in my `Cargo.toml`:

```
fluent-templates = "0.12.0"
leptos-fluent = "0.2.1"
```

But in my lock I get:

```
[[package]]
name = "leptos-fluent"
version = "0.2.1"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "327a46db61d335fe1cda2e4e68980c5c1b061d97e9fb338992546c215d3ce998"
dependencies = [
 "fluent-templates 0.12.0",
 "leptos",
 "leptos-fluent-macros",
 "leptos_meta",
 "web-sys",
]

[[package]]
name = "leptos-fluent-macros"
version = "0.2.1"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "af85dc2235461834ad3844d1c4c2c070248d329433bacda23b302771e43ec2b6"
dependencies = [
 "cfg-expr 0.15.8",
 "current_platform",
 "fluent-syntax",
 "fluent-templates 0.11.0",
 "globwalk",
 "pathdiff",
 "proc-macro2",
 "quote",
 "syn 2.0.91",
 "walkdir",
]
```

And you can see that there are 2 versions of `fluent-templates` and this gives a compiler error: `expected 'StaticLoader', found a different 'StaticLoader'`

ps. the main `README.md` points to the `0.11` version is that correct?

**Comment by mondeja** [comment]
[As you can see](https://github.com/mondeja/leptos-fluent/blob/9dc990fbc2469505c0894335d44617e71814f048/leptos-fluent-macros/Cargo.toml#L23), leptos-fluent-macros is pinning fluent-templates to `>=0.9`. What happens if you run `cargo update`?

> the main README.md points to the 0.11 version is that correct?

Nope, this needs to be fixed in docs.

**Comment by johansmitsnl** [comment]
@mondeja when I run cargo update it stays in the state I posted before. And leptos-fluent is the only one in my lock file that depends on leptos-fluent-macros.

**Comment by mondeja** [comment]
Looks like a bug in cargo. Try recreating the lock file. I don't know what else could be happening, so closing...
